export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
  },
  DASHBOARD: "/",
  PROJECTS: "/projects",
  CUSTOMERS: "/customers",
  LICENSES: "/licenses",
  REPORTS: "/reports",
  MAINTENANCE: "/maintenance",
  ANALYTICS: "/analytics",
  SETTINGS: "/settings",
  COMPANIES: "/companies",
  SUBSCRIPTIONS: "/subscriptions",
  USERS: "/users",
  REQUESTS: "/requests",
  EMPLOYEES: "/employees",
  BLUEPRINT_REVIEW: "/blueprint-review",
  QUOTATIONS: "/quotations",
  SITE_VISITS: "/site-visits",
  CALENDAR: "/calendar",
  EXECUTION: "/execution",
  EXPENSES: "/expenses",
  LABOR: "/labor",
  OBSTACLES: "/obstacles",
  DOCUMENTS: "/documents",
  LEADS: "/leads",
  PIPELINE: "/pipeline",
  COMMISSIONS: "/commissions",
  ACTIVITIES: "/activities",
  TRACKING: "/tracking",
  CONTRACTS: "/contracts",
  INVOICES: "/invoices",
  MESSAGES: "/messages",
  PROFILE: "/profile",
} as const;
