export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    REGISTER_COMPANY: "/register-company",
  },
  DASHBOARD: "/",
  PROJECTS: "/projects",
  CUSTOMERS: "/customers",
  LICENSES: "/licenses",
  REPORTS: "/reports",
  MAINTENANCE: "/maintenance",
  ANALYTICS: "/analytics",
  COMPANY_ADMIN: {
    ROOT: "/company-admin",
    OVERVIEW: "/company-admin/overview",
    STAFF: "/company-admin/staff",
  },
  SETTINGS: {
    ROOT: "/settings",
    GENERAL: "/settings/general",
    SEO: "/settings/seo",
    COMMUNICATION: "/settings/communication",
    POLICIES: "/settings/policies",
    SYSTEM: "/settings/system",
  },
  COMPANIES: "/companies",
  SUBSCRIPTIONS: "/subscriptions",
  USERS: "/users",
  REQUESTS: "/requests",
  EMPLOYEES: "/employees",
  BLUEPRINT_REVIEW: "/blueprint-review",
  QUOTATIONS: "/quotations",
  SITE_VISITS: "/site-visits",
  CALENDAR: "/calendar",
  LEADS: "/leads",
  PIPELINE: "/pipeline",
  COMMISSIONS: "/commissions",
  ACTIVITIES: "/activities",
  TRACKING: "/tracking",
  CONTRACTS: "/contracts",
  INVOICES: "/invoices",
  MESSAGES: "/messages",
  PROFILE: "/profile",
} as const;

